name: ocr_service

volumes:
  minio_data:
  ocr_model:

networks:
  ocr_service_vllm_ocr_network:
    external: true

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - ocr_service_vllm_ocr_network
    command: server --console-address ":9001" /data

  api:
    build: .
    image: api_image
    container_name: api
    environment:
      - MINIO_ENDPOINT=minio:9000
      - OCR_LLM_ENDPOINT=http://load-balancer:4377
      - MINIO_DOWNLOAD_URL=http://42.96.34.158:8001
      - MAX_CONCURRENT_TASKS=2
    ports:
      - 8001:8000
    networks:
      - ocr_service_vllm_ocr_network
    depends_on:
      - minio
